- name: Check if user exists
  ansible.builtin.command: getent passwd {{ item.user }}
  register: user_check_result
  ignore_errors: true
  changed_when: false

- name: Ensure user exists (change password if forced)
  become: true
  ansible.builtin.user:
    name: "{{ item.user }}"
    groups: "{{ item.groups }}"
    shell: /bin/bash
    password: "{{ (initial_password_salt ~ '@' ~ item.user) | hash('sha256') | password_hash('sha512') }}"
    password_expire_warn: 62
  when: user_check_result.failed == true
    or force_change_users_password

- name: Determine authorized‐key environment suffix
  ansible.builtin.set_fact:
    auth_key_env: >-
      {{ 'dev' 
         if is_dev  | default(false) 
         else 'production' }}

- name: "Set fact | Determine SSH Key Source"
  ansible.builtin.set_fact:
    current_key_secret: "{{ lookup('env', 'SSH_KEY_' + item.user | replace('.', '_') + '_' + auth_key_env, default='') }}"
    current_key_path: "{{ role_path }}/files/public_keys/{{ item.user }}_{{ auth_key_env }}.pub.key"

- name: Ensure authorized key is installed for user
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    state: present
    comment: "{{ item.user }}@{{ auth_key_env }}-ManagedByAnsible"
    # Use the secret from semaphore if found, otherwise perform the file lookup
    key: >-
      {{ current_key_secret if current_key_secret != '' 
         else lookup('file', current_key_path, errors='ignore') }}
  when:
    - auth_key_env is defined
    - (current_key_secret != '') or (current_key_path is file)
